### ISSUE TITLE
Build Errors following the instructions

### ISSUE THREAD

**Issue by ghost** [Wonicon/VerilogBlackBox#3]
Hello, thanks for developing this software. It is just what I'm looking for. 

However, I'm not able to build the software with the commands given in the README. 
There are a few things that go wrong: The first: 
```sh
java -x .

>>> outputs >>> 
Unrecognized option: x
Error: Could not create the Java Virtual Machine. 
Error: A fatal exception has occurred. Program will exit.
```

The second thing that goes wrong is:
```sh
java -cp antlr-4.6-complete.jar Verilog2001.g4
>>> Outputs >>> 
Error: Could not find or load main class Verilog2001.g4
Caused by: java.lang.ClassNotFoundException: Verilog2001.g4
```

I can change the ```cp``` to ```jar``` and get it to build the classes. However, when I then run 
```sh
java -cp . Main myVerilog.v >> BlackBox.scala

>>> it outputs >>> 
Error: Unable to initialize main class Main
Caused by: java.lang.NoClassDefFoundError: org/antlr/v4/runtime/CharStream
```
Can you help me out? 
Thanks!

**Comment by Wonicon** [comment]
Sorry for such a late response. The repo has not been under maintained for a long time. I also got confused by these instructions when trying to use the code yesterday. Anyway, I have transfered the code into a standard gradle project, hoping it can be more usable.
